on: [push, pull_request]

name: tests

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tc: [1.60.0, stable, beta, nightly]
        ar:
        - --all --no-default-features
        - --all --all-features
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: ${{ matrix.ar }}
